# Generated by Django 2.2 on 2020-11-08 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', models.CharField(blank=True, default='', max_length=45, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', mapbox_location_field.models.LocationField(map_attrs={'center': (-76.51972, 3.44), 'marker_color': 'DodgerBlue', 'style': 'mapbox://styles/mapbox/streets-v11'})),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', mapbox_location_field.models.AddressAutoHiddenField(map_id='map')),
                ('name', models.CharField(max_length=8)),
                ('level', models.IntegerField(choices=[(1, 'Grieta'), (2, 'Normal'), (3, 'Mortal')])),
                ('users', models.ManyToManyField(blank=True, related_name='places', to='holefy_app.Profile')),
            ],
        ),
    ]
